### ISSUE TITLE
headline color

### ISSUE THREAD

**Issue by dinotheextinct** [sspaeti/obsidian_kanagawa#2]
Hey thanks for sharing but I am looking to edit the headline colors, because h1 with super red is too aggressive for my liking. Can you comment the css lines or tell me which ones are the headlines?

**Comment by sspaeti** [comment]
You're welcome, happy you like it! :) Yeah sure, you can change it here: https://github.com/sspaeti/obsidian_kanagawa/blob/1adf4f59b14dbc159bcf4ec052c6dafda9e8d85e/obsidian.css#L108

You see `--neutral-red` is used, just change it to any color you like.

**Comment by sascha-wi** [comment]
Sadly I just updated my plugins an overwrite my customization. Is there a way to prevent from happening that?

**Comment by sspaeti** [comment]
> Sadly I just updated my plugins an overwrite my customization. Is there a way to prevent from happening that?

Yes there is, you can copy the [obsidian.css](https://github.com/sspaeti/obsidian_kanagawa/blob/main/obsidian.css) to your local `.obsidian/themes/` folder. Best to rename to something else e.g. `custom_kanagawa.css`, and you will see it as an alternative in your Obsidian:

<img width="1093" alt="image" src="https://github.com/sspaeti/obsidian_kanagawa/assets/689199/3a05ad77-2c04-4469-9f26-7f3af1db73e8">
