### ISSUE TITLE
bash code is kinda of bland

### ISSUE THREAD

**Issue by sascha-wi** [sspaeti/obsidian_kanagawa#3]
![image](https://user-images.githubusercontent.com/123939946/215445860-0943655d-52e5-4537-ace9-38abd456e461.png)
Is this to be expected? Not sure why main font color for shell is so dark compared to background.

**Comment by sspaeti** [comment]
@sascha-wi: This is how it looks on mine: 
![image](https://user-images.githubusercontent.com/689199/215987493-33950e5d-5518-46f6-b8a4-391d465c94a9.png)

Which seems quite ok to me. What color would you change it to?

But I just noticed, if I change to toggle live preview, it looks dark:
![image](https://user-images.githubusercontent.com/689199/215987314-91e4e15b-5de9-4b5f-bfc3-27eb5eb65684.png)

But tbh, I always use live preview, that's probably why I didn't notice.

**Comment by sascha-wi** [comment]
Maybe I am missing the point of code coloring, but that grey is such a low contrast compared to the background.
